-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "Description" TEXT DEFAULT 'NA',
ADD COLUMN     "code" TEXT NOT NULL DEFAULT 'NA',
ADD COLUMN     "manufacturer" TEXT DEFAULT 'NA',
ADD COLUMN     "mark" TEXT DEFAULT 'NA',
ADD COLUMN     "model" TEXT DEFAULT 'NA',
ADD COLUMN     "partNumber" TEXT NOT NULL DEFAULT 'NA',
ADD COLUMN     "quantity" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "uom" TEXT NOT NULL DEFAULT 'NA';
